In [165]:
import torch
#T  = X * U 
# We are finding U using torch
# let say X is data 100 sample and 50 dimentions
torch.manual_seed(0)
d = 50 # data dimention
r = 2 # pca dimention
X =  torch.tensor(torch.rand(100, d)) # Local Data
U = torch.tensor(torch.rand(d, r),requires_grad=True) # PCA parameter
I = torch.ones(d, d)

/Users/charlie/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
/Users/charlie/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if __name__ == '__main__':


In [181]:
if(U.grad is not None):
    U.grad.data.zero_()
Loss_FunTion = torch.norm(torch.mm((I - torch.mm(U, U.T)),X.T))**2
Loss_FunTion.backward()
print(U.grad.data[0:5], U.grad.data.shape)

tensor([[-56903.6445, -48494.0625],
        [-69675.1406, -59468.7852],
        [-76105.6641, -64955.4766],
        [-80627.3438, -68988.2031],
        [-47253.4336, -40074.4805]]) torch.Size([50, 2])


In [177]:
if(U.grad is not None):
    U.grad.data.zero_()
Loss_FunTion2 = torch.norm(torch.mm(X,(I - torch.mm(U, U.T))))**2
Loss_FunTion2.backward()
print(U.grad.data[0:5], U.grad.data.shape)

tensor([[-56903.6445, -48494.0586],
        [-69675.1406, -59468.7852],
        [-76105.6641, -64955.4766],
        [-80627.3438, -68988.1953],
        [-47253.4336, -40074.4805]]) torch.Size([50, 2])


In [174]:
if(U.grad is not None):
    U.grad.data.zero_()
A = torch.mm((I - torch.mm(U, U.T)),X.T)
C = torch.mm(U.T,X.T)
print(A.shape)
print(C.shape)

torch.Size([50, 100])
torch.Size([2, 100])


In [179]:
solution = -4 * torch.mm(A, C.T)
print(solution[0:5])

tensor([[ -54549.1562,  -47118.9141],
        [ -84184.5234,  -72589.6875],
        [ -95432.8359,  -82263.6406],
        [-109321.9375,  -94297.5859],
        [ -37640.4961,  -32421.2852]], grad_fn=<SliceBackward>)
